In [1]:
import pandas as pd
from datetime import datetime
import wm_tac_ops as ops
from ground_engine import GroundEngine, BattleContext
from create_units import build_brigade_template
from tactical_engine import tact_battle


def brigade_stat(df,level):

    return pd.pivot_table(df,
               columns='status',
              index=level,
              values='soldier_uid',
              aggfunc='count')



config = {
    "soldier_id": 10,
    "squad_id": 3,
    "platoon_id": 3,
    "company_id": 6,
    "battalion_id": 5,
    "armor_cnt": 50,
}

inf_df, armor_df = build_brigade_template(config)

with pd.ExcelWriter("player_brigade.xlsx", engine="openpyxl") as writer:
    inf_df.to_excel(writer, sheet_name="inf", index=False)
    armor_df.to_excel(writer, sheet_name="armor", index=False)



config = {
    "soldier_id": 10,
    "squad_id": 3,
    "platoon_id": 3,
    "company_id": 3,
    "battalion_id": 8,
    "armor_cnt": 20,
}

inf_df, armor_df = build_brigade_template(config)

with pd.ExcelWriter("enemy_brigade.xlsx", engine="openpyxl") as writer:
    inf_df.to_excel(writer, sheet_name="inf", index=False)
    armor_df.to_excel(writer, sheet_name="armor", index=False)


pl = pd.read_excel("player_brigade.xlsx")
en = pd.read_excel("enemy_brigade.xlsx")

In [2]:
len(pl)

2700

In [3]:
len(en)

2160

In [8]:


PLAYER_FILE = "player_brigade.xlsx"
ENEMY_FILE = "enemy_brigade.xlsx"

PLAYER_LEVEL = "battalion"
PLAYER_FORMATIONS = ["B1"]
PLAYER_ARMOR_COUNT = 19
PLAYER_COVER_RANGE = (0,1)

ENEMY_LEVEL = "battalion"
ENEMY_FORMATIONS = ["B2"]
ENEMY_ARMOR_COUNT = 0
ENEMY_COVER_RANGE = (1,1)

TARGET_UNITS_PER_SIDE = 6

MIN_BATTLES = 3
MAX_BATTLES = 15

DISTANCE_RANGE = (0, 2)
ELEVATION_RANGE = (0, 0)

PLAYER_OUTPUT_FILE = "player_brigade.xlsx"
ENEMY_OUTPUT_FILE = "enemy_brigade.xlsx"

#PLAYER_OUTPUT_FILE = "player_brigade_after_battle.xlsx"
#ENEMY_OUTPUT_FILE = "enemy_brigade_after_battle.xlsx"
LOG_OUTPUT_FILE = "tactical_battle_log.xlsx"

START_TIME = datetime(2026, 4, 19, 14, 0)
TIME_STEP_MINUTES = 15

TACTICAL_BUTTLE_NUM = 3
TACTICAL_COMMENT = 'Штурм леса перед михновичами'

files = {
    'PLAYER_FILE': PLAYER_FILE,
    'ENEMY_FILE': ENEMY_FILE,
    'PLAYER_OUTPUT_FILE': PLAYER_OUTPUT_FILE,
    'ENEMY_OUTPUT_FILE': ENEMY_OUTPUT_FILE,
    'LOG_OUTPUT_FILE': LOG_OUTPUT_FILE,
}


player_data = {'PLAYER_LEVEL':PLAYER_LEVEL,
        'PLAYER_FORMATIONS':PLAYER_FORMATIONS,
        'PLAYER_ARMOR_COUNT':PLAYER_ARMOR_COUNT,
               'PLAYER_COVER_RANGE':PLAYER_COVER_RANGE}

enemy_data = {'ENEMY_LEVEL':ENEMY_LEVEL,
        'ENEMY_FORMATIONS':ENEMY_FORMATIONS,
        'ENEMY_ARMOR_COUNT':ENEMY_ARMOR_COUNT,
              'ENEMY_COVER_RANGE':ENEMY_COVER_RANGE}

other_data = {
    'TARGET_UNITS_PER_SIDE': TARGET_UNITS_PER_SIDE,
    'MIN_BATTLES': MIN_BATTLES,
    'MAX_BATTLES': MAX_BATTLES,
    'DISTANCE_RANGE': DISTANCE_RANGE,
    'ELEVATION_RANGE': ELEVATION_RANGE,
    'START_TIME': START_TIME,

    'TACTICAL_BUTTLE_NUM': TACTICAL_BUTTLE_NUM,
    'TACTICAL_BATTLE_TIME': START_TIME,
    'TACTICAL_COMMENT': TACTICAL_COMMENT,
}

tact_battle(files, player_data, enemy_data, other_data)

start

C:\Users\Kirill\1) ONELIGHT APP\WM_calculations\force_manager.py:559: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0 3 0 0 2 0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  master_indexed.loc[common_uids, col] = changed_df.loc[common_uids, col]
C:\Users\Kirill\1) ONELIGHT APP\WM_calculations\force_manager.py:559: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0 0 0 0 0 0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  master_indexed.loc[common_uids, col] = changed_df.loc[common_uids, col]
C:\Users\Kirill\1) ONELIGHT APP\WM_calculations\force_manager.py:559: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[nan nan nan nan nan nan]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  master_indexed.loc[common_uids, col] = changed_df.loc[common_uids, col]
C:\Users\Kirill\1) ONELIGHT APP\WM_calculations\force_manager.py:559: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  master_indexed.loc[common_uids, col] = changed_df.loc[common_uids, col]
C:\Users\Kirill\1) ONELIGHT APP\WM_calculations\force_manager.py:559: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  master_indexed.loc[common_uids, col] = changed_df.loc[common_uids, col]
C:\Users\Kirill\1) ONELIGHT APP\WM_calculations\force_manager.py:559: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  master_indexed.loc[common_uids, col] = changed_df.loc[common_uids, col]

============================================================
Тактическая битва #3
Проведено наземных боёв: 6
------------------------------------------------------------
Общая статистика | победы blue: 6 | поражения blue: 0 | прочее: 0 | потери blue: 10 inf / 0 arm | потери red: 68 inf / 0 arm

Файлы сохранены:
- player_brigade.xlsx
- enemy_brigade.xlsx
- tactical_battle_log.xlsx

In [9]:
pl = pd.read_excel("player_brigade.xlsx")
en = pd.read_excel("enemy_brigade.xlsx")
brigade_stat(pl,'battalion_uid')

status         alive  killed
battalion_uid
B1             500.0    40.0
B2             540.0     NaN
B3             540.0     NaN
B4             540.0     NaN
B5             540.0     NaN

In [10]:
brigade_stat(en,'battalion_uid')

status         alive  killed
battalion_uid
B1             203.0    67.0
B2             153.0   117.0
B3             270.0     NaN
B4             270.0     NaN
B5             270.0     NaN
B6             270.0     NaN
B7             270.0     NaN
B8             270.0     NaN

In [21]:
364.0/1436.0

0.25348189415041783