In [ ]:
armor = pd.DataFrame([[1,'apc',9,8,0],
                  [2,'apc',9,8,0]],columns=['armor_id','type','transport','power','kill_count'])

In [1]:
from datetime import datetime, timedelta
import itertools
from collections import Counter
import matplotlib.pyplot as plt
import random 
from typing import Optional
##### import random
from collections import Counter
import wm_unit as wmu
import pandas as pd

def calculate_force(force):
    available_force = 0
    casualties = 0
    for i in force:
        available_force += len(i.alive_df)
        casualties += len(i.cas_df)
    return available_force,casualties

def next_turn(current_time):
    current_time += timedelta(minutes=15)
    print(current_time)
    return current_time


a1 = pd.read_excel('A1.xlsx').iloc[:25]
a2 = pd.read_excel('A1.xlsx').iloc[:25]
a3 = pd.read_excel('A1.xlsx').iloc[:25]
a4 = pd.read_excel('A1.xlsx').iloc[:25]
a5 = pd.read_excel('A1.xlsx').iloc[:25]
a6 = pd.read_excel('A1.xlsx').iloc[:75]

a1 = wmu.Unit(unit_id="a1",  alive_df=a1,  cas_df=pd.DataFrame(),side='red')
a2 = wmu.Unit(unit_id="a2",  alive_df=a2,  cas_df=pd.DataFrame(),side='red')
a3 = wmu.Unit(unit_id="a3",  alive_df=a3,  cas_df=pd.DataFrame(),side='red')
a4 = wmu.Unit(unit_id="a4",  alive_df=a4,  cas_df=pd.DataFrame(),side='red')
a5 = wmu.Unit(unit_id="a5",  alive_df=a5,  cas_df=pd.DataFrame(),side='red')
a6 = wmu.Unit(unit_id="a6",  alive_df=a6,  cas_df=pd.DataFrame(),side='red')

b1 = pd.read_excel('A1.xlsx').iloc[:100]
b2 = pd.read_excel('A1.xlsx').iloc[:100]
b1 = wmu.Unit(unit_id="b1",  alive_df=b1,  cas_df=pd.DataFrame(),side='blue')
b2 = wmu.Unit(unit_id="b2",  alive_df=b2,  cas_df=pd.DataFrame(),side='blue')

attackers = [b1,b2]
defenders = [a1,a2,a3,a4,a5,a6]

current_time = datetime(2026,1,9,6,0)
logs = pd.DataFrame()

In [33]:
a4 = pd.read_excel('A1.xlsx').iloc[:50]
a4 = wmu.Unit(unit_id="a4",  alive_df=a4,  cas_df=pd.DataFrame(),side='red')

In [ ]:
current_time = next_turn(current_time)

In [46]:
logs = a4.attack_unit(b1,logs,current_time)

        ######
        a4
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 0 ?

enemy_unit_id b2 ?

 b1

berserk_mode 0 ?

        ######
        b1
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 0 ?

enemy_unit_id a2 ?

 a4

berserk_mode 1 ?

a4  вжат землю
поражение
0.03 0.18
0 14

In [47]:
logs = a2.attack_unit(b1,logs,current_time)

        ######
        a2
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 0 ?

enemy_unit_id b1 ?

berserk_mode 0 ?

        ######
        b1
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 0 ?

enemy_unit_id a4 ?

berserk_mode 1 ?

атака без ответа
засада
0.03 0.65
0

In [42]:
current_time = next_turn(current_time)

2026-01-09 08:00:00

In [52]:
logs

,time,attack_unit_side,attack_unit,attack_unit_size,attack_unit_alive_force,attack_cas,defend_unit,defend_unit_size,defend_unit_alive_force,defend_cas,result
0,2026-01-09 06:00:00,blue,b1,CM,100,0,a6,CM,75,0,ничья
0,2026-01-09 06:15:00,blue,b1,CM,100,0,a6,CM,75,0,ничья
0,2026-01-09 06:30:00,blue,b1,CM,100,3,a6,CM,75,2,ничья
0,2026-01-09 06:45:00,blue,b1,CM,97,2,a6,CM,73,8,победа
0,2026-01-09 07:00:00,blue,b1,CM,95,0,a6,CM,65,20,разгром
0,2026-01-09 07:00:00,red,a1,PT,25,0,b1,CM,95,0,засада
0,2026-01-09 07:15:00,blue,b1,CM,95,0,a2,PT,25,0,ничья
0,2026-01-09 07:15:00,red,a3,PT,25,0,b1,CM,95,1,поражение
0,2026-01-09 07:15:00,blue,b2,CM,100,0,a1,PT,25,8,разгром
0,2026-01-09 07:30:00,blue,b1,CM,94,1,a2,PT,25,5,ничья
0,2026-01-09 07:30:00,red,a3,PT,25,0,b1,CM,93,0,поражение
0,2026-01-09 07:30:00,blue,b2,CM,100,28,a4,CM,50,1,поражение
0,2026-01-09 07:45:00,blue,b1,CM,93,0,a2,PT,20,6,разгром
0,2026-01-09 07:45:00,red,a3,PT,25,0,b1,CM,93,1,засада
0,2026-01-09 07:45:00,blue,b2,CM,72,22,a4,CM,49,1,засада
0,2026-01-09 08:00:00,red,a4,CM,48,14,b1,CM,92,0,поражение
0,2026-01-09 08:00:00,red,a2,PT,14,0,b1,CM,92,0,засада

In [53]:
logs[['attack_unit_side','attack_cas','defend_cas']].groupby('attack_unit_side').sum()

                  attack_cas  defend_cas
attack_unit_side
blue                      56          51
red                       14           2

In [49]:
calculate_force(attackers)

(142, 58)

In [54]:
calculate_force(defenders)

(151, 49)

In [55]:
a4

Unit(unit_id=a4, size=CM, alive_df=34, cas_df=16, last_parameters={'elev_pos': 0, 'cover_level': 2, 'target_distance': 0, 'enemy_unit_id': 'b1', 'berserk_mode': 0})